language: cpp
compiler: clang
before_install:
    - sudo apt-get update
    - sudo apt-get install libboost-dev
script: make UNIT_TESTS=OFF configure && make
env: CXXFLAGS=-stdlib=libc++
branches:
    only:
        - travis